steps:
  # Step 1: Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/subgraph/Vega.git']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mystic-pagoda-369007/vega-docker', '-f', 'Dockerfile', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mystic-pagoda-369007/vega-docker']

  # Step 4: Run Vega against the target website
  - name: 'gcr.io/mystic-pagoda-369007/vega-docker'
    args: ['--scan', 'http://example.com']
