steps:
  # Install nmap
  - name: 'ubuntu'
    args: ['bash', '-c', 'apt-get update && apt-get install -y nmap']

  # Scan companies.jbcl.cloud using nmap
  - name: 'gcr.io/cloud-builders/nmap'
    args: ['companies.jbcl.cloud']
