steps:
- name: "gcr.io/owasp-zap/zap2docker-stable"
  entrypoint: "zap-baseline.py"
  args: [
    "-t", "http://app.jobbatical.com",
    "-r", "report.html",
    "-x", "report.xml"
  ]
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "report.html", "gs://pentest-result/reports/report-$(date +%Y%m%d-%H%M%S).html"]
timeout: "1600s"
