steps:
- name: "gcr.io/cloud-builders/openscap"
  args: ["--verbose", "--report", "/workspace/report.html", "https://companies.jbcl.cloud"]
  dir: "./openscap"
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "openvas-scan", "openvas"]
  dir: "./openvas"
- name: "gcr.io/cloud-builders/docker"
  args: ["run", "-v", "$(pwd)/workspace:/workspace", "openvas-scan"]
  dir: "./openvas"
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - "gsutil cp workspace/report.html $(pwd)/report.html"
timeout: "1200s"
