steps:
  # Install OpenVAS
  - name: Install OpenVAS
    run: |
      sudo apt-get update
      echo "tzdata tzdata/Areas select Europe" | sudo debconf-set-selections
      echo "tzdata tzdata/Zones/Europe select Berlin" | sudo debconf-set-selections
      sudo apt-get install -y openvas9
    id: install_openvas