steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/example/repository.git', '.']
    
  # Install Vega dependencies
  - name: 'node'
    entrypoint: 'npm'
    args: ['install', 'vega']

  # Run Vega scan
  - name: 'node'
    entrypoint: 'npx'
    args: ['@vega/scanner']

  # Upload Vega report as an artifact
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'vega-report.html', 'gs://my-bucket/vega-report.html']
    env:
      - 'MY_BUCKET=gs://my-bucket'
      - 'REPORT=vega-report.html'
artifacts:
  objects:
    location: '$MY_BUCKET'
    paths: ['$REPORT']
