steps:
- name: "gcr.io/cloud-builders/wget"
  args: ["https://github.com/zaproxy/zaproxy/releases/tag/w2023-01-31.zip", "-O", "zap.zip"]
- name: "gcr.io/cloud-builders/unzip"
  args: ["zap.zip", "-d", "zap"]
- name: "gcr.io/owasp-zap/zap2docker-stable"
  entrypoint: "zap-baseline.py"
  args: [
    "-t", "http://app.jobbatical.com",
    "-r", "report.html",
    "-x", "report.xml"
  ]
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "report.html", "gs://dumduma/reports/report-$(date +%Y%m%d-%H%M%S).html"]
