provider "google" {
  project = "mystic-pagoda-369007"
  region  = "us-central1"
  zone    = "us-central1-c"
}

# Create a Windows Server VM instance
resource "google_compute_instance" "windows_server" {
  name         = "my-windows-server"
  machine_type = "n1-standard-2"
  boot_disk {
    initialize_params {
      image = "windows-server-2019-dc-core-v20220127"
    }
  }

  network_interface {
    network = "default"
    access_config {
    }
  }

  metadata = {
    windows-startup-script-ps1 = <<PS1
      # Set admin username and password
      $adminPassword = "my-admin-password" | ConvertTo-SecureString -AsPlainText -Force
      $userName = "my-admin-username"
      $credential = New-Object System.Management.Automation.PSCredential($userName, $adminPassword)
      net user $userName $adminPassword

      # Download and install Autofirma
      $autofirmaUrl = "https://afirma.redsara.es/clienteafirma-current"
      $autofirmaInstallPath = "C:\\Autofirma"

      # Create installation directory if it doesn't exist
      if(!(Test-Path $autofirmaInstallPath)) {
        New-Item -ItemType Directory -Path $autofirmaInstallPath
      }

      # Download and run the installer
      $installer = "$($autofirmaUrl)/AutoFirma_1_7_0.exe"
      $installerPath = "C:\\Autofirma_Installer.exe"
      Invoke-WebRequest -Uri $installer -OutFile $installerPath
      Start-Process -FilePath $installerPath -ArgumentList "/SILENT /INSTALLDIR=$($autofirmaInstallPath)" -Wait
    PS1
  }
}
