steps:
- name: 'docker.io/library/docker:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    mkdir /zap/wrk
#     docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -I \
#     -t https://www.example.com -g gen.conf -r testreport.html -I
# artifacts:
#   objects:
#     location: 'gs://dumduma'
#     paths:
#       - testreport.html
