steps:
- name: "gcr.io/cloud-builders/openscap"
  args: ["--verbose", "--report", "/workspace/report.html", "https://companies.jbcl.cloud"]
  volumes:
  - name: "vol"
    path: "/workspace"
  env:
  - "HOME=/builder/home"
  - "XDG_CACHE_HOME=/builder/home/.cache"
  - "XDG_CONFIG_HOME=/builder/home/.config"
  - "XDG_DATA_HOME=/builder/home/.local/share"
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "openvas-scan", "openvas"]
  dir: "./nmap"
  env:
  - "HOME=/builder/home"
  - "XDG_CACHE_HOME=/builder/home/.cache"
  - "XDG_CONFIG_HOME=/builder/home/.config"
  - "XDG_DATA_HOME=/builder/home/.local/share"
- name: "gcr.io/cloud-builders/docker"
  args: ["run", "-v", "vol:/workspace", "openvas-scan"]
  env:
  - "HOME=/builder/home"
  - "XDG_CACHE_HOME=/builder/home/.cache"
  - "XDG_CONFIG_HOME=/builder/home/.config"
  - "XDG_DATA_HOME=/builder/home/.local/share"
  timeout: "1200s"

disk:
  name: vol
  sizeGb: 10
  mountPoint: /workspace
