steps:
- name: "gcr.io/cloud-builders/wget"
  args: ["https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip"]
- name: "gcr.io/cloud-builders/unzip"
  args: ["ZAP_2.10.0_Core.zip", "-d", "/zap"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "my-zap-image", "."]
- name: "my-zap-image"
  entrypoint: "/zap/zap.sh"
  args: [
    "-cmd", "-quickurl", "https://www.example.com",
    "-quickprogress", "-quickout", "/workspace/zap_report.html"
  ]
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "/workspace/zap_report.html", "gs://my-bucket/zap_reports/$(date +%Y%m%d-%H%M%S).html"]
