steps:
  - name: dast-scan
    id: DAST Scan using OWASP ZAP
    dir: /workspace
    entrypoint: bash
    args:
      - -c
      - |
        cd /app/ZAP_2.12.0/
        ./zap.sh -cmd -quickurl https://app.jbcl.cloud -quickprogress -quickout ../zap_report.html
  - name: copy-report
    id: Copy report to bucket
    entrypoint: bash
    args:
      - -c
      - |
        gsutil cp /workspace/zap_report.html gs://pentest-result/
