# steps:
# - name: 'docker.io/library/docker:latest'
#   entrypoint: 'sh'
#   args:
#   - '-c'
#   - |
#     # Install Docker Compose
#     # curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#     # chmod +x /usr/local/bin/docker-compose

#     # Run the ZAP Full Scan on example.com
#     docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
#     -t https://www.example.com -g gen.conf -r testreport.html

steps:
- name: gcr.io/mystic-pagoda-369007/my-zap-image:latest
  args: ["zap-baseline.py", "-t", "http://example.com", "-r", "/zap/wrk/report.html"]
  volumeMounts:
  - name: zap-data
    mountPath: /zap/wrk
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "/workspace/zap-data/report.html", "gs://my-bucket/zap/reports/report_$(date +'%Y-%m-%d_%H-%M-%S').html"]
  volumeMounts:
  - name: zap-data
    mountPath: /zap/wrk

volumeMounts:
- name: zap-data
  gcePersistentDisk:
    pdName: zap-data
    fsType: ext4

