steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/IFGHou/Wapiti.git', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'wapiti', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'wapiti', '-u', 'https://example.com', '-o', 'report.html']
