steps:
- name: 'gcr.io/mystic-pagoda-369007/my-zap-image'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    docker run -t gcr.io/mystic-pagoda-369007/my-zap-image zap-full-scan.py -t https://www.example.com
