steps:
- name: 'ubuntu'
  entrypoint: bash
  args:
  - '-c'
  - |
    apt-get update
    echo "tzdata tzdata/Areas select Europe" | debconf-set-selections
    echo "tzdata tzdata/Zones/Europe select Berlin" | debconf-set-selections
    apt-get install -y openvas9
  id: Install OpenVAS
