steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/IFGHou/wapiti.git', '/workspace/wapiti']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'wapiti', '/workspace/wapiti']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '${PWD}:/report', 'wapiti', '-u', 'https://YOUR_WEBSITE_URL', '-f', 'html', '-o', '/report/wapiti-report.html']
