steps:
- name: 'docker.io/library/docker:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Docker Compose
    # curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    # chmod +x /usr/local/bin/docker-compose

    # Run the ZAP Full Scan on example.com
    docker run -t owasp/zap2docker-stable zap-full-scan.py -t https://www.example.com
