steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "openvas-scan", "-f", "Dockerfile", "."]
  dir: "openvas"
- name: "gcr.io/cloud-builders/docker"
  args: ["run", "-v", "$(pwd)/results:/results", "openvas-scan", "companies.jbcl.cloud"]
  timeout: "1200s"
