steps:
  - name: DAST Scan using OWASP ZAP
    run:
      image: gcr.io/global-mobility-services/jb-ops/jb4c-pentest:latest
      dir: /workspace
      entrypoint: bash
      args:
        - -c
        - |
          cd /app/ZAP_2.12.0/
          ./zap.sh -cmd -quickurl https://ww.example.com -quickprogress -quickout ../zap_report.html
    id: DAST Scan using OWASP ZAP
  - name: copy-report
    id: Copy report to bucket
    entrypoint: bash
    args:
      - -c
      - |
        gsutil cp /workspace/zap_report.html gs://pentest-result/
