steps:
  # Install OpenVAS
  - name: install_openvas
    entrypoint: bash
    args:
      - '-c'
      - |
        sudo apt-get update
        echo "tzdata tzdata/Areas select Europe" | sudo debconf-set-selections
        echo "tzdata tzdata/Zones/Europe select Berlin" | sudo debconf-set-selections
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:mrazavi/gvm
        sudo apt-get update
        sudo apt-get install -y gvm
        sudo gvm-setup
    id: install_openvas
