steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sullo/nikto.git', '/workspace/nikto']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'nikto', '.']
  dir: '/workspace/nikto/program'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '${PWD}:/nikto', 'nikto', '-h', 'https://app.jbcl.cloud/', '-output', '/nikto/report.html']
  dir: '/workspace/nikto/program'
