steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    docker run -t gcr.io/mystic-pagoda-369007/my-zap-image zap-full-scan.py -t https://www.example.com -r testreport.html -I
#  artifacts:
#   objects:
#     location: 'gs://dumduma'
#     paths:
#       - zap/wrk/zap_report.html
