steps:
  - name: "docker.io/snyk/snyk-cli:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        snyk test --docker mystic-pagoda-369007/vega-lite:v1 --file=Dockerfile --severity-threshold=high --json-file-output=result.json
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "cp"
      - "result.json"
      - "gs://your-bucket/result.json"
Ë˜
