steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/nmap/nmap.git']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'nmap', '-f', 'nmap/Dockerfile', '.']
  dir: 'nmap'
- name: gcr.io/cloud-builders/docker
  args: ['run', '-v', '/workspace:/output', 'nmap', '-oX', '/output/results.xml', 'example.com']
- name: gcr.io/cloud-builders/scp
  args: ['-r', '-P', '22', '/workspace/results.xml', 'user@host:/path/to/remote/file']
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/greenbone/openvas.git']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'openvas', '-f', 'openvas/Dockerfile', '.']
  dir: 'openvas'
- name: gcr.io/cloud-builders/docker
  args: ['run', '-v', '/workspace:/output', 'openvas', '-oX', '/output/results.xml', 'example.com']
