steps:
- name: "docker.io/schmunk42/vega-ci"
  args: ["--target", "https://example.com", "--dir", "/tmp", "--report", "/report/report.html"]
  volumes:
  - name: "report"
    path: "/report"
  timeout: "300s"

volumes:
- name: "report"
  path: "/report"

options:
  volumes:
    - name: "report"
      path: "gs://my-bucket/reports"

