steps:   
#Run DAST scan using OWASP ZAP in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - -c
      - |
        - apt-get update
        - apt-get -y install wget
        - apt-get -y install default-jdk
        - wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
        - mkdir zap
        - tar -xvf ZAP_2.12.0_Linux.tar.gz
        - cd ZAP_2.12.0
        - ./zap.sh -addoninstallall -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html -spider -ajaxspider -active_scan -recursive 5 -scanners all
  - id: DAST Scan using OWASP ZAP
