steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    docker run -v $(pwd):/zap/wrk/:rw --user root -t gcr.io/global-mobility-services/test:latest zap-full-scan.py \
    -t https://app.jobbatical.com -I  -r testreport.html
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "testreport.html", "gs://pentest-result/reports/report-$(date +%Y%m%d-%H%M%S).html"]
