steps:
- name: "gcr.io/mystic-pagoda-369007/my-zap-image:latest"
  entrypoint: "zap-baseline.py"
  args: [
    "-t", "http://example.com",
    "-r", "report.html",
    "-x", "report.xml"
  ]
  volumes:
  - name: "workdir"
    path: "/zap/wrk"
- name: "gcr.io/cloud-builders/gsutil"
  args: ["cp", "report.html", "gs://my-bucket/reports/report-$(date +%Y%m%d-%H%M%S).html"]
  volumes:
  - name: "workdir"
    path: "/zap/wrk"
