steps:
  # Checkout the source code
  - name: 'gcr.io/cloud-builders/git'
    id: Checkout
    args:
      - 'clone'
      - '--'
      - 'https://github.com/your-web-app.git'
      - '.'
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: Install dependencies
    args: ['install']
  # Run Vega DAST scan
  - name: 'owasp/dependency-check'
    id: Vega DAST scan
    entrypoint: 'dependency-check'
    args:
      - '-P'
      - '-f'
      - 'HTML'
      - '-s'
      - '.'
  # Upload Vega DAST scan report to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Upload Vega DAST scan report
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FILE=$(find . -name 'dependency-check-report.html')
        if [ -f "$FILE" ]; then
          gsutil cp "$FILE" gs://your-bucket-name/vega-report/$(date +%Y-%m-%d-%H-%M-%S)-vega-report.html
        else
          echo "No Vega DAST scan report found."
        fi
images:
  - gcr.io/your-project-id/your-web-app

